name: note_app
description: A simple notes app that demonstrates Provider and ChangeNotifier for app-wide state with local persistence.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
