name: reminder_app
description: A simple reminder app demonstrating local notifications with flutter_local_notifications and a DateTime picker.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^12.0.4
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
