name: weather_app
description: A simple Weather app demonstrating geolocation, http, FutureBuilder and JSON parsing.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  geolocator: ^9.0.2

flutter:
  uses-material-design: true
