name: expense_tracker_app
description: A minimal expense tracker app using Hive for local storage and fl_chart for graphs.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.60.0

flutter:
  uses-material-design: true
