name: personal_profile_app
description: A minimal personal profile app demonstrating layout, responsive UI and dark mode toggle.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  # If you add a local profile image, place it at assets/profile.jpg and uncomment below:
  # assets:
  #   - assets/profile.jpg
